"""Update discussions table for file uploads

Revision ID: 761c9dc82812
Revises: aee7e270b53d
Create Date: 2024-06-20 04:39:29.552289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761c9dc82812'
down_revision: Union[str, None] = 'aee7e270b53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussions', sa.Column('file_path', sa.String(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index('ix_users_mobile_no', table_name='users')
    op.create_index(op.f('ix_users_mobile_no'), 'users', ['mobile_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile_no'), table_name='users')
    op.create_index('ix_users_mobile_no', 'users', ['mobile_no'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('discussions', 'file_path')
    # ### end Alembic commands ###
